# Generated by Django 3.2.7 on 2021-10-15 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User'},
        ),
    ]
