# Generated by Django 3.2 on 2021-10-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_goal', '0003_auto_20211015_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goals',
            name='publish_status',
            field=models.IntegerField(default=1),
        ),
    ]
