# Generated by Django 3.2 on 2021-10-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_goal', '0004_auto_20211021_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
