# Generated by Django 3.2.7 on 2021-10-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_goal', '0006_auto_20211024_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
