# Generated by Django 3.2.7 on 2021-10-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_forum', '0003_auto_20211016_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='report_times',
            field=models.IntegerField(default=0),
        ),
    ]
