# Generated by Django 3.2.7 on 2021-10-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_profile', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unikey',
        ),
    ]
