# Generated by Django 3.2.7 on 2021-10-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_profile', '0003_remove_user_unikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_code_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
