# Generated by Django 3.2.7 on 2021-10-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_profile', '0005_alter_user_email_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_code_time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
